dist: xenial
addons:
  apt:
    packages:
      - libqt5gui5
language: python
branches:
  only:
    - master
python:
  - "2.7"
  - "3.6"
env:
  - PHYSBIBLIO_CONFIG="."
  - PHYSBIBLIO_DATA="."
install: python setup.py install
script: ./PhysBiblio.exe test
