#!/usr/bin/env python
"""
Main file for the PhysBiblio application, a bibliography manager written in Python.

This file is part of the physbiblio package.
"""

import sys

try:
	from physbiblio import __version__, __version_date__
	from physbiblio.argParser import *
except ImportError:
    print("Could not find physbiblio and its contents: configure your PYTHONPATH!")
    raise

if __name__=='__main__':
	if len(sys.argv) > 1:
		parser = setParser()
		args = parser.parse_args(sys.argv[1:])
		args.func(args)
	else:
		call_gui()
