[tox]
envlist = ruff,{py310,py3}-{pyside6_min,pyside6_curr},online
toxworkdir={env:TOX_WORK_DIR:.tox}

[testenv:ruff]
deps =
  ruff
basepython = python3
commands =
  ruff check --fix
  ruff check --select I --fix
  ruff format
  
[testenv]
passenv =
  DISPLAY
  XAUTHORITY
setenv =
  QT_QPA_PLATFORM=minimal
deps =
  pyside6_min: pyside6==6.6.0
  pyside6_curr: pyside6
commands =
  python PhysBiblio.exe test -o

[testenv:online]
basepython = python3
deps =
  pyside6
commands =
  python PhysBiblio.exe test
