class CommonStrings:
    """Some common strings for the package"""

    cancel = "Cancel"
    default = "Default"
    deleteQ = "Delete?"
    description = "Description"
    doneD = "Done."
    doneE = "Done!"
    errorInvalidParent = "Cannot run %s: invalid parent"
    filename = "Filename"
    information = "Information"
    load = "Load"
    noAttribute = "%s has no attribute '%s'"
    nothingFound = "Nothing found."
    ok = "OK"
    opening = "Opening '%s'..."
    openingFailed = "Opening %s for '%s' failed!"
    order = "Order"
    question = "Question"
    shortName = "Short name"
