class CommonStrings:
    """Some common strings for the package"""

    andC = "AND"
    cancel = "Cancel"
    close = "Close"
    default = "Default"
    delete = "Delete"
    deleteQ = "Delete?"
    description = "Description"
    doneD = "Done."
    doneE = "Done!"
    error = "Error"
    errorInvalidParent = "Cannot run %s: invalid parent"
    false = "False"
    filename = "Filename"
    information = "Information"
    load = "Load"
    modify = "Modify"
    noAttribute = "%s has no attribute '%s'"
    nothingFound = "Nothing found."
    ok = "OK"
    opening = "Opening '%s'..."
    openingFailed = "Opening %s for '%s' failed!"
    orC = "OR"
    order = "Order"
    question = "Question"
    save = "Save"
    shortName = "Short name"
    true = "True"
    warning = "Warning"
