"""Module that contains the PBBibTexWriter class
(needed to override _entry_to_bibtex).

This file is part of the physbiblio package.
"""

import traceback

import bibtexparser

try:
    from physbiblio.strings.main import BibtexWriterStrings as bwstr
except ImportError:
    print("Could not find physbiblio and its modules!")
    print(traceback.format_exc())


class PBBibTexWriter:
    """This class is used to store the configuration for bibtexparser.write"""

    def __init__(self):
        """Constructor for the PBBibTexWriter class.
        Uses parent class constructor
        and adds some additional properties.
        """
        self.bwriterconfig = bibtexparser.BibtexFormat()
        # order of fields in output
        self.display_order = [
            "author",
            "collaboration",
            "title",
            "booktitle",
            "publisher",
            "journal",
            "volume",
            "year",
            "pages",
            "russian",
            "archiveprefix",
            "primaryclass",
            "eprint",
            "doi",
            "reportNumber",
        ]
        self.bracket_fields = [
            "title",
            "booktitle",
            "www",
            "note",
            "abstract",
            "comment",
            "article",
            "url",
        ]
        self.excluded_fields = ["adsnote", "adsurl", "slaccitation", "ENTRYTYPE", "ID"]

    def getNewLibrary(self, string=""):
        """Create a new bibtexparser.Library"""
        if isinstance(string, str) and string:
            return bibtexparser.parse_string(string)
        return bibtexparser.Library()

    def reorderEntry(self, entry):
        """Reorder Fields from an existing Entry"""
        keys = [f.key for f in entry.fields]
        fields = [i for i in self.display_order if i in keys]
        # then all the other fields sorted alphabetically
        fields += [
            i
            for i in sorted(keys)
            if i not in self.display_order and i not in self.excluded_fields
        ]
        fields = [entry.fields_dict[k] for k in fields]
        return bibtexparser.model.Entry(entry.entry_type, entry.key, fields)

    def olddict2Entry(self, dic):
        """Convert an old dict to a new Entry"""
        fields = [i for i in self.display_order if i in dic]
        # then all the other fields sorted alphabetically
        fields += [
            i
            for i in sorted(dic)
            if i not in self.display_order and i not in self.excluded_fields
        ]
        fields = [bibtexparser.model.Field(k, dic[k]) for k in fields]
        return bibtexparser.model.Entry(dic["ENTRYTYPE"], dic["ID"], fields)

    def olddict2Library(self, dic):
        """Convert an old dict to a new Entry and add it to a new Library"""
        lib = self.getNewLibrary()
        if isinstance(dic, dict):
            lib.add(self.olddict2Entry(dic))
        elif isinstance(dic, list):
            for d in dic:
                lib.add(self.olddict2Entry(d))
        return lib

    def entry2Olddict(self, entry):
        """Convert a new Entry to an old dict"""
        dic = {i.key: i.value for i in entry.fields}
        dic["ENTRYTYPE"] = entry.entry_type
        dic["ID"] = entry.key
        return dic

    def library2Olddict(self, lib):
        """Convert a new Library to an old dict"""
        dictlist = []
        for entry in lib.entries:
            dic = {i.key: i.value for i in entry.fields}
            dic["ENTRYTYPE"] = entry.entry_type
            dic["ID"] = entry.key
            dictlist.append(dic)
        return dictlist

    def _entry_to_bibtex(self, entry):
        """Redefine the function that writes
        the entries in the bib file.
        Adapted from
        `bibtexparser.bwriter.BibTexWriter._entry_to_bibtex`.

        Parameters:
            entry: a dictionary generated by bibtexparser.

        Output:
            the bibtex string
        """
        bibtex = ""
        # Write BibTeX key
        bibtex += (
            "@"
            + entry["ENTRYTYPE"].capitalize()
            + "{"
            + (entry["ID"] if entry["ID"] is not None else "")
        )

        # create display_order of fields for this entry
        # first those keys which are both
        # in self.display_order and in entry.keys
        display_order = [i for i in self.display_order if i in entry]
        # then all the other fields sorted alphabetically
        display_order += [
            i
            for i in sorted(entry)
            if i not in self.display_order and i not in self.excluded_fields
        ]

        # Write field = value lines
        for field in [i for i in display_order if i not in ("ENTRYTYPE", "ID")]:
            try:
                entry[field] = entry[field].replace("{{{", "{").replace("}}}", "}")
                bibtex += (
                    ",\n"
                    + self.indent
                    + "{0:>{1}}".format(field, self._max_field_width)
                    + ' = "'
                    + (
                        "{" + entry[field] + "}"
                        if field in self.bracket_fields
                        and (entry[field][0] != "{" or entry[field][-1] != "}")
                        else entry[field]
                    )
                    + '"'
                )
            except TypeError:
                raise TypeError(bwstr.errorNotString % (field, entry["ID"]))
        bibtex += ",\n}\n" + self.entry_separator
        return bibtex

    def _reorder_entry_fields(self, lib):
        """NYI"""
        return lib
        olib = self.getNewLibrary()
        for e in lib.entries:
            olib.add(self.reorderEntry(e))
        print(olib.entries)
        return olib

    def write(self, lib):
        """simple function wrapper"""
        olib = self._reorder_entry_fields(lib)
        return bibtexparser.write_string(olib)

    def writeOld(self, db):
        return self.write(self.olddict2Library(db))

    def rewrite(self, bibtex):
        return self.write(self.getNewLibrary(bibtex))


pbWriter = PBBibTexWriter()
